version: "3.9"
services:
    mongodb:
        image: 'mongo:5.0.2'
        container_name: mongoctr # Don't really need this. Can refer using the service name given above without using the container name
        volumes:
            - ./data:/data/db
        # environment: Adding to env file
        #     # Below syntax works as well
        #     # - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        #     # - MONGO_INITDB_ROOT_PASSWORD=secret
        #     MONGO_INITDB_ROOT_USERNAME: mongoadmin
        #     MONGO_INITDB_ROOT_PASSWORD: secret
        env_file: # Good idea to add this to .gitignroe and not check in
            - ./env/mongo.env
        # networks: 
        #     - test-network
        # Docker compose by default adds all services into same network. 
    backend:
        # Short form
        # build: ./backend
        image: docker-test-api:initial
        build:
            context: ./backend
            dockerfile: Dockerfile # No need as this is default
            args:
                - DEFAULT_PORT=8080
        container_name: test_api
        ports:
            - '8081:8081'
        env_file: 
            - ./env/api.env
        volumes:
            - /app/node_modules
            - ./backend:/app
        depends_on: 
            - mongodb
    frontend:
        image: docker-test-app:initial
        build:
            context: ./frontend
            args:
                - DEFAULT_PORT=3000
                - DEFAULT_API_PORT=8081
        container_name: test_app
        ports:
            - '8080:3000'
        env_file: 
            - ./env/ui.env
        volumes:
            - ./frontend/src:/app/src:ro
            - /app/node_modules
        # -it is handled from below
        stdin_open: true
        tty: true
        depends_on: 
            - backend
